import { redirect } from 'next/navigation'
import { CalendarDays, CheckCircle2, CircleAlert } from 'lucide-react'
import { getCurrentUser } from '@/lib/auth/current-user'
import { getWorkspaceUserId } from '@/lib/admin-accounts/queries'
import { DEAL_STATUS_LABELS, DEAL_TYPE_LABELS, listDealEvents } from '@/lib/operations/deal-calendar'
import { createDealEventAction, updateDealStatusAction } from './actions'

export const dynamic = 'force-dynamic'
const won = (n: number | null) => n == null ? '-' : `${n.toLocaleString('ko-KR')}원`
export default async function DealCalendarPage() {
  const user = await getCurrentUser(); if (!user) redirect('/login')
  const events = await listDealEvents(await getWorkspaceUserId(user.id))
  const todos = events.filter((e) => ['submitted', 'selected'].includes(e.status))
  return <div className="space-y-5">
    <header><h1 className="flex items-center gap-2 text-2xl font-semibold"><CalendarDays className="h-6 w-6"/>딜 캘린더</h1><p className="mt-1 text-sm text-muted-foreground">톡딜 제안 일정, 판매 조건과 후속 투두를 한곳에서 관리합니다.</p></header>
    <section className="grid gap-3 md:grid-cols-3"><Summary label="7/27~8/2 제안" value={events.length}/><Summary label="제안 완료" value={events.filter(e=>e.status==='submitted').length}/><Summary label="남은 투두" value={todos.length}/></section>
    <section className="rounded-lg border bg-card p-4"><h2 className="mb-3 font-semibold">2026년 7월 · 카카오 톡딜</h2><div className="grid grid-cols-7 gap-1 text-center text-xs text-muted-foreground">{['월','화','수','목','금','토','일'].map(d=><div key={d}>{d}</div>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{Array.from({length:35},(_,i)=>{const day=i-1; const active=day>=27&&day<=31; return <div key={i} className={`min-h-24 rounded border p-1 ${active?'border-blue-300 bg-blue-50':''}`}><span className="text-xs">{day>0&&day<=31?day:''}</span>{day===27&&events.map(e=><div key={e.id} className="mt-1 truncate rounded bg-blue-600 px-1 py-0.5 text-[10px] text-white">{DEAL_TYPE_LABELS[e.dealType]} · {e.title}</div>)}</div>})}</div></section>
    <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><section className="space-y-3">{events.map(e=><article key={e.id} className="rounded-lg border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="rounded bg-slate-100 px-2 py-1 text-xs font-medium">{DEAL_TYPE_LABELS[e.dealType]}</span><h3 className="mt-2 font-semibold">{e.title}</h3><p className="text-xs text-muted-foreground">상품코드 {e.productCode} · {e.startsOn}~{e.endsOn}</p></div><b className="text-blue-700">{won(e.dealPrice)}</b></div>{e.options&&<p className="mt-3 text-xs">옵션: {e.options}</p>}<p className="mt-2 text-xs text-muted-foreground">재고 {e.stock} · 일 출고 {e.dailyCapacity} · 원가 {won(e.unitCost)} · 배송비 {won(e.shippingCost)}</p><form action={updateDealStatusAction} className="mt-3 flex gap-2"><input type="hidden" name="id" value={e.id}/><select name="status" defaultValue={e.status} className="h-8 rounded border bg-background px-2 text-xs">{Object.entries(DEAL_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="rounded bg-slate-900 px-3 text-xs text-white">상태 저장</button></form></article>)}</section>
      <aside className="space-y-4"><section className="rounded-lg border bg-card p-4"><h2 className="flex items-center gap-2 font-semibold"><CircleAlert className="h-4 w-4"/>투두</h2><div className="mt-3 space-y-3">{todos.map(e=><div key={e.id} className="rounded border p-3 text-sm"><b>{e.status==='submitted'?'선정 결과 확인':'톡딜 할인·무배 설정'}</b><p className="mt-1 text-xs text-muted-foreground">{DEAL_TYPE_LABELS[e.dealType]} · {e.title}</p><p className="mt-1 text-xs">{e.status==='submitted'?'제안 결과 메일 확인 후 상태를 선정/미선정으로 변경':'17시 시작, 79시간 할인 및 무료배송 확인'}</p></div>)}{!todos.length&&<p className="flex gap-2 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4"/>남은 투두가 없습니다.</p>}</div></section>
      <form action={createDealEventAction} className="space-y-2 rounded-lg border bg-card p-4"><h2 className="font-semibold">새 딜 추가</h2><select name="dealType" className="w-full rounded border p-2 text-sm">{Object.entries(DEAL_TYPE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input required name="title" placeholder="상품명" className="w-full rounded border p-2 text-sm"/><input name="productCode" placeholder="상품코드" className="w-full rounded border p-2 text-sm"/><input required name="dealPrice" type="number" placeholder="딜 판매가" className="w-full rounded border p-2 text-sm"/><div className="grid grid-cols-2 gap-2"><input required name="startsOn" type="date" defaultValue="2026-07-27" className="rounded border p-2 text-sm"/><input required name="endsOn" type="date" defaultValue="2026-08-02" className="rounded border p-2 text-sm"/></div><button className="w-full rounded bg-blue-600 p-2 text-sm font-medium text-white">캘린더에 추가</button></form></aside></div>
  </div>
}
function Summary({label,value}:{label:string,value:number}) { return <div className="rounded-lg border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div> }
